{
    "type": "bundle",
    "id": "bundle--247f4860-2b2c-49b0-9557-0ca5ef1105b0",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--78a63172-eb96-4c6c-9881-69da5b65e5bd",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2024-04-03T00:53:29.881947Z",
            "modified": "2024-04-03T00:53:29.881947Z",
            "name": "CVE-2023-42962",
            "description": "This issue was addressed with improved checks This issue is fixed in iOS 17.2 and iPadOS 17.2, iOS 16.7.3 and iPadOS 16.7.3. A remote attacker may be able to cause a denial-of-service.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2023-42962"
                }
            ]
        }
    ]
}