{
    "type": "bundle",
    "id": "bundle--dcbeb70e-67fe-41ea-9441-351b28bf0fd3",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--778cd029-71d2-4923-82ac-a11d627944ea",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2024-04-25T00:57:54.997083Z",
            "modified": "2024-04-25T00:57:54.997083Z",
            "name": "CVE-2024-32879",
            "description": "Python Social Auth is a social authentication/registration mechanism. Prior to version 5.4.1, due to default case-insensitive collation in MySQL or MariaDB databases, third-party authentication user IDs are not case-sensitive and could cause different IDs to match. This issue has been addressed by a fix released in version 5.4.1. An immediate workaround would be to change collation of the affected field.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2024-32879"
                }
            ]
        }
    ]
}