{
    "type": "bundle",
    "id": "bundle--475d5d79-291d-49ad-a3c7-c02879bbd687",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--a045b8ab-c964-4bf1-ae74-8f6fd6c65344",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2024-06-13T00:59:41.650619Z",
            "modified": "2024-06-13T00:59:41.650619Z",
            "name": "CVE-2024-37300",
            "description": "OAuthenticator is software that allows OAuth2 identity providers to be plugged in and used with JupyterHub. JupyterHub < 5.0, when used with `GlobusOAuthenticator`, could be configured to allow all users from a particular institution only. This worked fine prior to JupyterHub 5.0, because `allow_all` did not take precedence over `identity_provider`. Since JupyterHub 5.0, `allow_all` does take precedence over `identity_provider`. On a hub with the same config, now all users will be allowed to login, regardless of `identity_provider`. `identity_provider` will basically be ignored. This is a documented change in JupyterHub 5.0, but is likely to catch many users by surprise. OAuthenticator 16.3.1 fixes the issue with JupyterHub 5.0, and does not affect previous versions. As a workaround, do not upgrade to JupyterHub 5.0 when using `GlobusOAuthenticator` in the prior configuration.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2024-37300"
                }
            ]
        }
    ]
}